### ISSUE TITLE
No qualifying bean of type 'com.fastcheck.timesheet.common.session.SpringSessionRepository' available: expected at least 1 bean which qualifies as autowire candidate.

### ISSUE THREAD

**Issue by pavankjadda** [Mati20041/spring-session-jpa-repository#2]
Hello,
I am trying to use your code in Eclipse with Maven. I got following exception. "**No qualifying bean of type 'com.fastcheck.timesheet.common.session.SpringSessionRepository' available: expected at least 1 bean which qualifies as autowire candidate**."

I do not see any implementation for "SpringSessionRepository" interface and auto wiring it in JPASessionRepository class. Am I missing something here? source code uploaded in github at following location https://github.com/jpavanaryan/FastCheck/blob/FormLogin/src/main/java/com/fastcheck/timesheet/common/session/SessionRepositoryImpl.java

**Comment by Mati20041** [comment]
Hi @jpavanaryan :)

Sorry for taking so long - I hurry to answer your question.

Please take a look at SpringSessionRepository 

`public interface SpringSessionRepository extends CrudRepository<SessionEntity, String>{
}`

As you can see this repository extends CrudRepository from SpringData. Having this as a super interface tells Spring to implement and create it automatically. Maybe you had some problems with correct starters in your pom.xml (please take a look)? It is hard to tell because your repo looks like did change and I don't know about which revision (commit) are you talking about.

Still, good look with your project!
